# Generated by Django 5.0.6 on 2024-06-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('descricao', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'verbose_name': 'Benefício',
                'verbose_name_plural': 'Benefícios',
            },
        ),
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('nome', models.CharField(max_length=50, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('departamento', models.CharField(max_length=50, null=True)),
                ('benefícios', models.ManyToManyField(blank=True, to='app_funcionarios_beneficios.beneficios')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
        ),
    ]
