# Generated by Django 5.0.6 on 2024-06-14 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_funcionarios_beneficios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=13)),
            ],
            options={
                'verbose_name': 'Telefone',
                'verbose_name_plural': 'Telefones',
            },
        ),
        migrations.AddField(
            model_name='funcionarios',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='funcionarios',
            name='telefone',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_funcionarios_beneficios.telefone'),
        ),
    ]
