# Generated by Django 5.0.6 on 2024-06-15 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_funcionarios_beneficios', '0005_departamentos_remove_funcionarios_departamento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionarios',
            old_name='departamento',
            new_name='departamentos',
        ),
    ]
