# Generated by Django 5.0.6 on 2024-06-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_funcionarios_beneficios', '0006_rename_departamento_funcionarios_departamentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficios',
            name='nome',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
