# Generated by Django 5.0.6 on 2024-06-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_funcionarios_beneficios', '0007_alter_beneficios_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficios',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
